<?php

namespace Application\Sonata\MediaBundle\Entity;

use Sonata\MediaBundle\Entity\BaseMedia as BaseMedia;

/**
 * This file has been generated by the SonataEasyExtendsBundle.
 *
 * @link https://sonata-project.org/easy-extends
 *
 * References:
 * @link http://www.doctrine-project.org/projects/orm/2.0/docs/reference/working-with-objects/en
 */
class Media extends BaseMedia
{
    /**
     * @var int $id
     */
    protected $id;

    /**
     * @var string
     */
    protected $role;

    /**
     * @return string
     */
    public function getFileOriginalUrl()
    {
        return $this->fileOriginalUrl;
    }

    /**
     * @param string $fileOriginalUrl
     */
    public function setFileOriginalUrl($fileOriginalUrl = null)
    {
        $this->fileOriginalUrl = $fileOriginalUrl;
    }

    /**
     * @var string
     */
    protected $fileUrl;

    /**
     * @var string
     */
    protected $fileOriginalUrl;

    /**
     * Get id.
     *
     * @return int $id
     */
    public function getId()
    {
        return $this->id;
    }
    /**
     * Constructor
     */
    public function __construct()
    {
        $this->galleryHasMedias = new \Doctrine\Common\Collections\ArrayCollection();
    }

    /**
     * Add galleryHasMedia.
     *
     * @param \Application\Sonata\MediaBundle\Entity\GalleryHasMedia $galleryHasMedia
     *
     * @return Media
     */
    public function addGalleryHasMedia(\Application\Sonata\MediaBundle\Entity\GalleryHasMedia $galleryHasMedia)
    {
        $this->galleryHasMedias[] = $galleryHasMedia;

        return $this;
    }

    /**
     * Remove galleryHasMedia.
     *
     * @param \Application\Sonata\MediaBundle\Entity\GalleryHasMedia $galleryHasMedia
     *
     * @return boolean TRUE if this collection contained the specified element, FALSE otherwise.
     */
    public function removeGalleryHasMedia(\Application\Sonata\MediaBundle\Entity\GalleryHasMedia $galleryHasMedia)
    {
        return $this->galleryHasMedias->removeElement($galleryHasMedia);
    }

    /**
     * Set category.
     *
     * @param \Application\Sonata\ClassificationBundle\Entity\Category|null $category
     *
     * @return Media
     */
    public function setCategory(\Application\Sonata\ClassificationBundle\Entity\Category $category = null)
    {
        $this->category = $category;

        return $this;
    }

    /**
     * Set role.
     *
     * @param string|null $role
     *
     * @return Media
     */
    public function setRole($role = null)
    {
        $this->role = $role;

        return $this;
    }

    /**
     * Get role.
     *
     * @return string|null
     */
    public function getRole()
    {
        return $this->role;
    }

    /**
     * Set url.
     *
     * @param string|null $role
     *
     * @return Media
     */
    public function setFileUrl($url = null)
    {
        $this->fileUrl = $url;

        return $this;
    }

    /**
     * Get url.
     *
     * @return string|null
     */
    public function getFileUrl()
    {
        return $this->fileUrl;
    }
}
