<?php

namespace Application\Sonata\PageBundle;

use Symfony\Component\HttpKernel\Bundle\Bundle;

use Symfony\Component\DependencyInjection\ContainerBuilder;

use Application\Sonata\PageBundle\DependencyInjection\Compiler\OverrideServiceCompilerPass;
use Sonata\CoreBundle\Form\FormHelper;
use Sonata\PageBundle\DependencyInjection\Compiler\CacheCompilerPass;
use Sonata\PageBundle\DependencyInjection\Compiler\CmfRouterCompilerPass;
use Sonata\PageBundle\DependencyInjection\Compiler\GlobalVariablesCompilerPass;
use Sonata\PageBundle\DependencyInjection\Compiler\PageServiceCompilerPass;
use Sonata\PageBundle\Form\Type\ApiBlockType;
use Sonata\PageBundle\Form\Type\ApiPageType;
use Sonata\PageBundle\Form\Type\ApiSiteType;
use Sonata\PageBundle\Form\Type\CreateSnapshotType;
use Sonata\PageBundle\Form\Type\PageSelectorType;
use Sonata\PageBundle\Form\Type\PageTypeChoiceType;
use Sonata\PageBundle\Form\Type\TemplateChoiceType;
use Symfony\Cmf\Bundle\RoutingBundle\Form\Type\RouteTypeType;

/**
 * This file has been generated by the SonataEasyExtendsBundle.
 *
 * @link https://sonata-project.org/easy-extends
 *
 * References:
 * @link http://symfony.com/doc/current/book/bundles.html
 */
class ApplicationSonataPageBundle extends Bundle
{
    /**
     * {@inheritdoc}
     */
    public function getParent()
    {
        return 'SonataPageBundle';
    }

    public function build(ContainerBuilder $container)
    {
        $container->addCompilerPass(new OverrideServiceCompilerPass());
    }
//
//    /**
//     * {@inheritdoc}
//     */
//    public function boot()
//    {
//        $this->registerFormMapping();
//    }
//
//    /**
//     * Register form mapping information.
//     */
//    public function registerFormMapping()
//    {
//        FormHelper::registerFormTypeMapping([
//            'sonata_page_api_form_site' => ApiSiteType::class,
//            'sonata_page_api_form_page' => ApiPageType::class,
//            'sonata_page_api_form_block' => ApiBlockType::class,
//            'sonata_page_selector' => PageSelectorType::class,
//            'sonata_page_create_snapshot' => CreateSnapshotType::class,
//            'sonata_page_template' => TemplateChoiceType::class,
//            'sonata_page_type_choice' => PageTypeChoiceType::class,
//            'cmf_routing_route_type' => RouteTypeType::class,
//        ]);
//    }
}