imports:
    - { resource: config.yml }

doctrine:
    orm:
        entity_managers:
            default:
                second_level_cache:
                    region_cache_driver:
                        type: service
                        id: snc_second_level_cache
                    enabled: true
                    region_lifetime: 86400
                    regions:
                        one_hour:
                            cache_driver:
                                type: service
                                id: snc_second_level_cache
                            lifetime: 3600
monolog:
    handlers:
        main:
            type: fingers_crossed
            action_level: error
            handler: nested
        nested:
            type: stream
            path: '%kernel.logs_dir%/%kernel.environment%.log'
            level: debug
        console:
            type: console
            process_psr_3_messages: false

snc_redis:
    clients:
        default:
            type: predis
            alias: default
            dsn: "redis://%redis.password%@%redis.host%"
            logging: '%kernel.debug%'
        doctrine:
            type: predis
            alias: doctrine
            dsn: "redis://%redis.password%@%redis.host%"
            logging: '%kernel.debug%'

    doctrine:
        metadata_cache:
            client: doctrine
            entity_manager: default
            namespace: 'dmc:'
        result_cache:
            client: doctrine
            entity_manager: default
            namespace: 'drc:'
        query_cache:
            client: doctrine
            entity_manager: default
            namespace: 'dqc:'
        second_level_cache:
            client: doctrine
            entity_manager: default
            namespace: 'dslc:'
