
admin_area:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: '%base_routes_prefix%/admin'

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: '%base_routes_prefix%/admin'

sonata_cache_cache:
    resource: '@SonataCacheBundle/Resources/config/routing/cache.xml'
    prefix: /

sonata_page_exceptions:
    resource: '@SonataPageBundle/Resources/config/routing/exceptions.xml'
    prefix: /

sonata_page_cache:
    resource: '@SonataPageBundle/Resources/config/routing/cache.xml'
    prefix: /

gallery:
    resource: '@SonataMediaBundle/Resources/config/routing/gallery.xml'
    prefix: /media/gallery

media:
    resource: '@SonataMediaBundle/Resources/config/routing/media.xml'
    prefix: /media

sonata_user_admin_security:
    resource: '@SonataUserBundle/Resources/config/routing/admin_security.xml'
    prefix: '%base_routes_prefix%/admin'

sonata_user_admin_resetting:
    resource: '@SonataUserBundle/Resources/config/routing/admin_resetting.xml'
    prefix: '%base_routes_prefix%/admin/resetting'

JMSTranslationBundle_ui:
    resource: "@JMSTranslationBundle/Controller/"
    type:     annotation
    prefix:   /admin/_trans

#news:
#    resource: '@SonataNewsBundle/Resources/config/routing/news.xml'
#    prefix: /news

#NelmioApiDocBundle:
#    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
#    prefix:   '%base_routes_prefix%/api/doc'
#
#sonata_api_page:
#    type:         rest
#    prefix:       '%base_routes_prefix%/api/page'
#    resource:     "@SonataPageBundle/Resources/config/routing/api.xml"

#sonata_api_news:
#    type:         rest
#    prefix:       '%base_routes_prefix%/api'
#    resource:     "@SonataNewsBundle/Resources/config/routing/api.xml"

#sonata_api_media:
#    type:         rest
#    prefix:       '%base_routes_prefix%/api'
#    resource:     "@SonataMediaBundle/Resources/config/routing/api.xml"

#sonata_api_slider:
#    type:         rest
#    prefix:       '%base_routes_prefix%/api/slider'
#    resource:     "@ApplicationSonataSliderBundle/Resources/config/routing/api.xml"

#sonata_api_product:
#    type:         rest
#    prefix:       '%base_routes_prefix%/api/product'
#    resource:     "@ApplicationSonataProductBundle/Resources/config/routing/api.xml"

#sonata_api_category:
#    type:         rest
#    prefix:       '%base_routes_prefix%/api'
#    resource:     "@SonataClassificationBundle/Resources/config/routing/api.xml"

#sonata_user:
#    type:         rest
#    prefix:       '%base_routes_prefix%/api'
#    resource:     "@SonataUserBundle/Resources/config/routing/api.xml"
#
#api_login_check:
#    path: '%base_routes_prefix%/api/login'


application_sonata_offer:
    prefix:   '%base_routes_prefix%/projekty'
    resource: "@ApplicationSonataOfferBundle/Resources/config/routing.yml"

_application_sonata_main:
    prefix:   '%base_routes_prefix%/main'
    resource: "@ApplicationSonataMainBundle/Resources/config/routing.yml"

iamgine:
    resource: '@LiipImagineBundle/Resources/config/routing.yaml'

