services:
#    application_sonata_slider.example:
#        class: Application\Sonata\SliderBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    application_sonata_slider.admin.slider:
        class: Application\Sonata\SliderBundle\Admin\SliderAdmin
        arguments: [~, Application\Sonata\SliderBundle\Entity\Slider, ApplicationSonataSliderBundle:SliderAdmin]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Slider, label: Slider }
        public: true
        calls:
            - [ addChild, [ "@application_sonata_slider.admin.slideritem" ] ]

    application_sonata_slider.admin.slideritem:
        class: Application\Sonata\SliderBundle\Admin\SliderItemAdmin
        arguments: [~, Application\Sonata\SliderBundle\Entity\SliderItem, ApplicationSonataSliderBundle:SliderItemAdmin]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Slider, label: SliderItem, show_in_dashboard: false }
        public: true
