<?php

namespace Application\Sonata\OfferBundle\Entity;

/**
 * OfferAttributeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OfferAttributeRepository extends \Doctrine\ORM\EntityRepository
{
}
