<?php

namespace Application\Sonata\PageBundle\Entity;

use Sonata\PageBundle\Entity\BaseSite as BaseSite;

/**
 * This file has been generated by the SonataEasyExtendsBundle.
 *
 * @link https://sonata-project.org/easy-extends
 *
 * References:
 * @link http://www.doctrine-project.org/projects/orm/2.0/docs/reference/working-with-objects/en
 */
class Site extends BaseSite
{
    /**
     * @var int $id
     */
    protected $id;

    /**
     * Get id.
     *
     * @return int $id
     */
    public function getId()
    {
        return $this->id;
    }
    /**
     * @var string|null
     */
    private $headCode;

    /**
     * @var string|null
     */
    private $footerCode;


    /**
     * Set headCode.
     *
     * @param string|null $headCode
     *
     * @return Site
     */
    public function setHeadCode($headCode = null)
    {
        $this->headCode = $headCode;

        return $this;
    }

    /**
     * Get headCode.
     *
     * @return string|null
     */
    public function getHeadCode()
    {
        return $this->headCode;
    }

    /**
     * Set footerCode.
     *
     * @param string|null $footerCode
     *
     * @return Site
     */
    public function setFooterCode($footerCode = null)
    {
        $this->footerCode = $footerCode;

        return $this;
    }

    /**
     * Get footerCode.
     *
     * @return string|null
     */
    public function getFooterCode()
    {
        return $this->footerCode;
    }
    /**
     * @var string|null
     */
    private $bodyCode;


    /**
     * Set bodyCode.
     *
     * @param string|null $bodyCode
     *
     * @return Site
     */
    public function setBodyCode($bodyCode = null)
    {
        $this->bodyCode = $bodyCode;

        return $this;
    }

    /**
     * Get bodyCode.
     *
     * @return string|null
     */
    public function getBodyCode()
    {
        return $this->bodyCode;
    }
}
